using UnityEngine;

namespace CosmicCatch.Player
{
    /// <summary>
    /// Runtime copy of the approved movement numbers from
    /// Docs/Data/balance.v0.1.json ("movement"). The asset is generated by the
    /// editor setup; do not edit values here or in the asset without updating
    /// the balance document in the same change.
    /// </summary>
    [CreateAssetMenu(fileName = "PlayerMovement", menuName = "Cosmic Catch/Player Movement")]
    public sealed class PlayerMovementDefinition : ScriptableObject
    {
        [Tooltip("Walk speed, m/s (balance: movement.speed).")]
        public float speed = 5f;

        [Tooltip("Jump apex height, m (balance: movement.jumpHeight).")]
        public float jumpHeight = 1.2f;

        [Tooltip("Regular gravity, m/s^2 (balance: movement.gravity).")]
        public float gravity = 9.81f;

        [Tooltip("Low-gravity zone acceleration (balance: movement.lowGravity).")]
        public float lowGravity = 3f;

        [Tooltip("Seconds to blend between gravities (balance: movement.gravityBlendSeconds).")]
        public float gravityBlendSeconds = 0.3f;

        [Tooltip("Half extent of the bounded play area on X/Z.")]
        public float playAreaHalfExtent = 8.5f;

        [Tooltip("Falling below this Y respawns the player before HP exists (DEV-005).")]
        public float killY = -20f;

        [Tooltip("Respawn point, must sit on the playable floor.")]
        public Vector3 spawnPoint = new Vector3(6f, 1.2f, -6f);
    }
}
